name: "Run Use Cases"
description: "Run METplus Use Cases"
author: "mccabe@ucar.edu"

inputs:
  dockerhubTag:
    description: 'Docker image to build'
    required: true
  categories:
    description: 'Use case category or categories to run (separate by comma)'
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dockerhubTag }}
    - ${{ inputs.categories }}